### ISSUE TITLE
linux 5.3

### ISSUE THREAD

**Issue by protonesso** [edward6/reiser4#7]
Can you make patches for Linux 5.3?

**Comment by edward6** [comment]
Later. If you can not wait, then try to build with reiser4-for-5.2, and let me know if any problems.

**Comment by protonesso** [comment]
Okay!

**Comment by protonesso** [comment]
here's an error:
```
In file included from ./include/linux/linkage.h:7,
                 from ./include/linux/kernel.h:8,
                 from fs/fs-writeback.c:17:
./include/linux/export.h:81:20: error: redefinition of '__kstrtab___inode_attach_wb'
   81 |  static const char __kstrtab_##sym[]    \
      |                    ^~~~~~~~~~
./include/linux/export.h:120:25: note: in expansion of macro '___EXPORT_SYMBOL'
  120 | #define __EXPORT_SYMBOL ___EXPORT_SYMBOL
      |                         ^~~~~~~~~~~~~~~~
./include/linux/export.h:127:2: note: in expansion of macro '__EXPORT_SYMBOL'
  127 |  __EXPORT_SYMBOL(sym, "_gpl")
      |  ^~~~~~~~~~~~~~~
fs/fs-writeback.c:293:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
  293 | EXPORT_SYMBOL_GPL(__inode_attach_wb);
      | ^~~~~~~~~~~~~~~~~
./include/linux/export.h:81:20: note: previous definition of '__kstrtab___inode_attach_wb' was here
   81 |  static const char __kstrtab_##sym[]    \
      |                    ^~~~~~~~~~
./include/linux/export.h:120:25: note: in expansion of macro '___EXPORT_SYMBOL'
  120 | #define __EXPORT_SYMBOL ___EXPORT_SYMBOL
      |                         ^~~~~~~~~~~~~~~~
./include/linux/export.h:127:2: note: in expansion of macro '__EXPORT_SYMBOL'
  127 |  __EXPORT_SYMBOL(sym, "_gpl")
      |  ^~~~~~~~~~~~~~~
fs/fs-writeback.c:253:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
  253 | EXPORT_SYMBOL_GPL(__inode_attach_wb);
      | ^~~~~~~~~~~~~~~~~
  CC [M]  net/netfilter/nf_synproxy_core.o
```

**Comment by edward6** [comment]
Could you please comment/remove expression "EXPORT_SYMBOL_GPL(__inode_attach_wb);" in the file fs/fs-writeback.c, line 293 and try to rebuild

**Comment by protonesso** [comment]
Later

**Comment by protonesso** [comment]
>Could you please comment/remove expression "EXPORT_SYMBOL_GPL(__inode_attach_wb);" in the file fs/fs-writeback.c, line 293 and try to rebuild
works!

**Comment by edward6** [comment]
Great.
