### ISSUE TITLE
linux-4.20

### ISSUE THREAD

**Issue by ShadyGaDa** [edward6/reiser4#2]
reiser4-for-4.18.0.patch.gz @sourceforge not appeared in github only reiser4-for-4.17.0.patch.gz ?
I am eager to try linux-4.20 however 4.18.0.patch errors on build jnode.c
with changed include/linux/xarray.c
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initially with xarray......etc.
then further after cut and paste of format41 code over top.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:)--------------------------------- very long beard drinking vodka eating sausages.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fs/reiser4/jnode.c: In function ‘inode_attach_jnode’:
fs/reiser4/jnode.c:421:11: error: ‘struct xarray’ has no member named ‘rnode’
  if (rtree->rnode == NULL) {
           ^~
fs/reiser4/jnode.c:424:32: error: ‘struct address_space’ has no member named ‘tree_lock’; did you mean ‘private_lock’?
   spin_lock_irq(&inode->i_data.tree_lock);
                                ^~~~~~~~~
                                private_lock
fs/reiser4/jnode.c:426:34: error: ‘struct address_space’ has no member named ‘tree_lock’; did you mean ‘private_lock’?
   spin_unlock_irq(&inode->i_data.tree_lock);
                                  ^~~~~~~~~
                                  private_lock
fs/reiser4/jnode.c: In function ‘inode_detach_jnode’:
fs/reiser4/jnode.c:452:11: error: ‘struct xarray’ has no member named ‘rnode’
  if (rtree->rnode == NULL) {
           ^~
fs/reiser4/jnode.c:454:32: error: ‘struct address_space’ has no member named ‘tree_lock’; did you mean ‘private_lock’?
   spin_lock_irq(&inode->i_data.tree_lock);
                                ^~~~~~~~~
                                private_lock
fs/reiser4/jnode.c:456:34: error: ‘struct address_space’ has no member named ‘tree_lock’; did you mean ‘private_lock’?
   spin_unlock_irq(&inode->i_data.tree_lock);
                                  ^~~~~~~~~
                                  private_lock
make[2]: *** [fs/reiser4/jnode.o] Error 1
make[1]: *** [fs/reiser4] Error 2
make: *** [fs] Error 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dubrovnik.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by edward6** [comment]
"format41" branch is supposed to work with linux-4.14 for now.
Please, don't file missing ports as "reiser4 issue".
Thanks.

**Comment by ShadyGaDa** [comment]
Only filed to clarify what other branch was for.
Mainly to find out when you would be releasing 4.20?
So just the first error is ‘struct xarray’ has no member named ‘rnode’.

**Comment by edward6** [comment]
Reiser4 for Linux-4.20 will be released a bit later.
"format41" is development (not stable) branch. It can be used only in conjunction with "format41" branch of reiser4progs.
